(defpackage 3b-walker
  (:use :c2cl)
  (:local-nicknames (:a :alexandria.2))
  (:export
   #:binding
   #:variable-binding
   #:free-variable
   #:host-variable
   #:scoped-variable-binding
   #:required-variable-binding
   #:scoped-variable-binding-with-p
   #:suppliedp-variable-binding
   #:optional-variable-binding
   #:rest-variable-binding
   #:key-variable-binding
   #:aux-variable-binding
   #:constant-binding
   #:symbol-macro-binding
   #:name
   #:context
   #:initform
   #:specialp
   #:pvar-binding
   #:keyname
   #:value
   #:expansion
   #:function-binding
   #:host-function
   #:cmacro
   #:host-macro
   #:expander
   #:implicit-progn
   #:body
   #:form-with-declarations
   #:declarations
   #:form-with-docstring
   #:docstring
   #:lambda-function
   #:lambda-list
   #:bindings
   #:local-function
   #:global-function
   #:macro-binding
   #:whole
   #:block-binding
   #:go-tag-binding
   #:unknown-go-tag-binding
   #:lexical-environment
   #:variables
   #:functions
   #:setf-functions
   #:blocks
   #:lock
   #:ast-node
   #:variable-reference
   #:constant-reference
   #:symbol-macro-reference
   #:original-form
   #:application
   #:lambda-application
   #:func
   #:args
   #:normal-application
   #:function-application
   #:compiler-macro-application
   #:original-expansion
   #:macro-application
   #:special-form-application
   #:special-form-catch
   #:tag-ast
   #:special-form-eval-when
   #:situations
   #:special-form-function
   #:special-form-go
   #:tag
   #:special-form-if
   #:test
   #:then
   #:else
   #:elsep
   #:special-form-load-time-value
   #:form
   #:read-only
   #:special-form-multiple-value-call
   #:function-form
   #:special-form-multiple-value-prog1
   #:first-form
   #:special-form-progn
   #:special-form-progv
   #:symbols-ast
   #:values-ast
   #:special-form-quote
   #:object
   #:special-form-return-from
   #:result
   #:special-form-the
   #:typespec
   #:special-form-throw
   #:special-form-unwind-protect
   #:protected-form
   #:special-form-setq
   #:value-asts
   #:special-form-block
   #:special-form-flet
   #:special-form-labels
   #:special-form-macrolet
   #:special-form-let
   #:special-form-let*
   #:special-form-symbol-macrolet
   #:special-form-locally
   #:special-form-tagbody
   #:ast->sexp
   #:collapse-macros
   #:validate-ast
   #:ast-stats
   #:cons->ast
   #:progn->ast
   #:walk-ast
   #:filter-ast
   #:copy-node
   #:sexp->ast))
